'use strict';
const ICONS={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',check:'<path d="M9 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-8M8 11l4 4L22 4"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8M8 17h5"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18M8 15h2M14 15h2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/>',people:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[n]||ICONS.file}</svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PEOPLE={lin:{name:'林知夏',dept:'产品设计部',color:'blue',baseline:{annual:5,comp:1}},chen:{name:'陈予安',dept:'产品设计部',color:'violet',baseline:{annual:4,comp:0}},xu:{name:'许沐',dept:'研发部',color:'coral',baseline:{annual:3,comp:2}},zhou:{name:'周亦然',dept:'市场部',color:'green',baseline:{annual:6,comp:0}},shen:{name:'沈清禾',dept:'产品设计部',color:'gold',baseline:{annual:4,comp:1}},lu:{name:'陆星野',dept:'研发部',color:'cyan',baseline:{annual:2,comp:0}}};
const TYPES={annual:'年假',comp:'调休',personal:'事假'};const STATUSES={pending:'待审批',approved:'已通过',rejected:'已驳回',withdrawn:'已撤回'};const BASE_DATE='2026-09-30';const KEY='leaveflow-demo-v1';
const SEED=[
{id:'LF-2026-0108',person:'chen',type:'annual',start:'2026-10-12',end:'2026-10-13',startHalf:'am',endHalf:'pm',days:2,reason:'计划短途休息，项目工作将提前交接给沈清禾。',status:'pending',created:'2026-09-30',note:''},
{id:'LF-2026-0107',person:'xu',type:'comp',start:'2026-10-09',end:'2026-10-09',startHalf:'pm',endHalf:'pm',days:.5,reason:'安排个人事务，上午完成本周的代码评审。',status:'pending',created:'2026-09-30',note:''},
{id:'LF-2026-0106',person:'zhou',type:'personal',start:'2026-10-14',end:'2026-10-14',startHalf:'am',endHalf:'pm',days:1,reason:'处理个人事务，活动资料已完成整理。',status:'pending',created:'2026-09-29',note:''},
{id:'LF-2026-0105',person:'shen',type:'annual',start:'2026-10-19',end:'2026-10-21',startHalf:'am',endHalf:'pm',days:3,reason:'安排一次秋日旅行，设计稿将在休假前交付。',status:'approved',created:'2026-09-28',note:'交接安排清楚，祝假期愉快。',reviewed:'2026-09-29'},
{id:'LF-2026-0104',person:'lin',type:'annual',start:'2026-09-22',end:'2026-09-23',startHalf:'am',endHalf:'pm',days:2,reason:'个人休假，部门日常事务已安排交接。',status:'approved',created:'2026-09-18',note:'同意，工作已妥善安排。',reviewed:'2026-09-18'},
{id:'LF-2026-0103',person:'lu',type:'comp',start:'2026-09-25',end:'2026-09-25',startHalf:'am',endHalf:'pm',days:1,reason:'使用调休余额，相关任务提前完成。',status:'approved',created:'2026-09-21',note:'同意。',reviewed:'2026-09-22'},
{id:'LF-2026-0102',person:'chen',type:'annual',start:'2026-09-15',end:'2026-09-15',startHalf:'am',endHalf:'pm',days:1,reason:'安排个人休息。',status:'approved',created:'2026-09-10',note:'同意，请按计划交接。',reviewed:'2026-09-11'},
{id:'LF-2026-0101',person:'chen',type:'personal',start:'2026-09-09',end:'2026-09-10',startHalf:'am',endHalf:'pm',days:2,reason:'个人行程安排。',status:'rejected',created:'2026-09-07',note:'与产品评审时间冲突，请调整日期后重新申请。',reviewed:'2026-09-07'}
];
let records=structuredClone(SEED),role='manager',view='overview',filter={query:'',status:'all',type:'all'},dashTab='pending',toastTimer;let storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&saved.version===1&&Array.isArray(saved.records)&&saved.records.every(r=>r&&PEOPLE[r.person]&&TYPES[r.type]&&STATUSES[r.status]&&typeof r.days==='number'&&r.days>0&&/^\d{4}-\d{2}-\d{2}$/.test(r.start)&&/^\d{4}-\d{2}-\d{2}$/.test(r.end))){records=saved.records;role=saved.role==='employee'?'employee':'manager';}}catch(e){storageAvailable=false;}
const $=id=>document.getElementById(id);const who=()=>role==='manager'?'lin':'chen';const user=()=>PEOPLE[who()];const own=()=>records.filter(r=>r.person===who());const pending=()=>records.filter(r=>r.status==='pending'&&r.person!==who());const shortDate=s=>s.slice(5).replace('-','.');const dateRange=r=>r.start===r.end?`${shortDate(r.start)} ${r.startHalf==='am'?'上午':'下午'} — ${r.endHalf==='am'?'上午':'下午'}`:`${shortDate(r.start)} ${r.startHalf==='am'?'上午':'下午'} — ${shortDate(r.end)} ${r.endHalf==='am'?'上午':'下午'}`;
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,records,role}));}catch(e){storageAvailable=false;toast('浏览器未允许保存，当前操作将在关闭页面后丢失');}}
function balance(person,type){const total=type==='annual'?15:4;const used=PEOPLE[person].baseline[type]+records.filter(r=>r.person===person&&r.type===type&&r.status==='approved').reduce((s,r)=>s+r.days,0);const reserved=records.filter(r=>r.person===person&&r.type===type&&r.status==='pending').reduce((s,r)=>s+r.days,0);return {total,used,reserved,left:Math.max(0,total-used-reserved)};}
function duration(start,end,startHalf='am',endHalf='pm'){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||end<start)return 0;const a=new Date(start+'T12:00:00Z'),b=new Date(end+'T12:00:00Z');if(!Number.isFinite(+a)||!Number.isFinite(+b)||(b-a)/864e5>366)return 0;let sum=0;for(let d=new Date(a);d<=b;d.setUTCDate(d.getUTCDate()+1)){if(d.getUTCDay()!==0&&d.getUTCDay()!==6){let h=1;if(+d===+a&&startHalf==='pm')h-=.5;if(+d===+b&&endHalf==='am')h-=.5;sum+=h;}}return Math.max(0,sum);}
function overlaps(a,b){const a0=a.start+(a.startHalf==='am'?'0':'1'),a1=a.end+(a.endHalf==='am'?'0':'1'),b0=b.start+(b.startHalf==='am'?'0':'1'),b1=b.end+(b.endHalf==='am'?'0':'1');return a0<=b1&&b0<=a1;}
const pill=r=>`<span class="pill ${r.status}">${STATUSES[r.status]}</span>`;const avatar=person=>`<span class="avatar ${PEOPLE[person].color}">${PEOPLE[person].name[0]}</span>`;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
function navigate(next){view=next;filter={query:'',status:'all',type:'all'};if(role==='employee'&&view==='approvals')view='records';history.replaceState(null,'','#'+view);$('sidebar').classList.remove('open');render();}
function header(title,eyebrow,subtitle){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div><div class="head-tools"><button class="button primary" data-action="apply">${icon('plus')} 发起请假</button></div></div>`;}
function renderNav(){const navs=[['overview','grid','工作台'],...(role==='manager'?[['approvals','check','审批中心']]:[]),['records','file',role==='manager'?'请假记录':'我的申请'],['balances','sun','我的假期']];$('nav').innerHTML=navs.map(([v,i,t])=>`<button class="nav-item ${view===v?'active':''}" data-nav="${v}">${icon(i)}${t}${v==='approvals'&&pending().length?`<span class="nav-count">${pending().length}</span>`:''}</button>`).join('');$('breadcrumbTitle').textContent=navs.find(n=>n[0]===view)?.[2]||'工作台';$('profileAvatar').textContent=user().name[0];$('profileText').innerHTML=`${user().name}<small>${role==='manager'?'部门主管':'产品设计师'} · 演示身份</small>`;$('roleSelect').value=role;}
function metric(label,value,unit,foot,i){return `<div class="metric"><div class="metric-label">${label}${icon(i)}</div><div class="metric-number">${value}<small>${unit}</small></div><div class="metric-foot">${foot}</div></div>`;}
function annualCard(){const b=balance(who(),'annual');return `<section class="panel"><div class="panel-head"><h2>我的年假</h2><button class="text-link" data-nav="balances">查看假期</button></div><div class="balance-card"><div class="balance-top"><div class="donut" style="--ratio:${b.left/b.total*100}"><div class="donut-inner"><strong>${b.left}<span style="font-size:12px;margin-left:3px">天</span></strong><span>可用余额</span></div></div><div class="balance-legend"><strong>2026 年度</strong><div><span class="legend-key"></span>可用 ${b.left} 天</div><div><span class="legend-key pale"></span>年度额度 ${b.total} 天</div></div></div><div class="balance-item"><span>已批准</span><strong>${b.used} 天</strong></div><div class="balance-item"><span>审批中预占</span><strong>${b.reserved} 天</strong></div><div class="balance-note">年度假期有效期至 2026.12.31<br>余额与规则仅用于演示</div></div></section>`;}
function calendarCard(){let cells='';for(let i=0;i<3;i++)cells+=`<div class="calendar-day muted">${28+i}</div>`;for(let day=1;day<=31;day++){let d='2026-10-'+String(day).padStart(2,'0');let count=records.filter(r=>r.status==='approved'&&r.start<=d&&r.end>=d&&![0,6].includes(new Date(d+'T12:00:00Z').getUTCDay())).length;cells+=`<div class="calendar-day ${count?'leave':''}" title="10月${day}日${count?'，'+count+'人已批准休假':''}">${day}</div>`;}cells+='<div class="calendar-day muted">1</div>';return `<section class="panel"><div class="panel-head"><h2>团队休假日历</h2><span class="tiny-count">10 月</span></div><div class="calendar"><div class="calendar-top"><span>2026 年 10 月</span><span>${icon('calendar').replace('<svg','<svg style="width:16px;height:16px"')}</span></div><div class="calendar-grid">${['一','二','三','四','五','六','日'].map(s=>`<div class="weekday">${s}</div>`).join('')}${cells}</div><div class="calendar-legend"><span></span>已批准休假 · 周一至周五</div></div></section>`;}
function empty(title,desc,button=false){return `<div class="empty-state"><span class="empty-symbol">◇</span><strong>${title}</strong>${desc}${button?'<br><button class="button small" data-action="clear-filters">清除筛选</button>':''}</div>`;}
function requestRows(list){if(!list.length)return empty('一切都已安排妥当','暂无需要处理的请假申请');return `<div class="approval-list">${list.map(r=>`<div class="approval-row">${avatar(r.person)}<div class="request-summary"><div class="request-first"><strong>${PEOPLE[r.person].name}</strong><span class="department">${PEOPLE[r.person].dept}</span><span class="leave-type">${TYPES[r.type]}</span></div><div class="request-dates">${dateRange(r)} <strong>· ${r.days} 天</strong></div><div class="request-reason">${esc(r.reason)}</div></div><div class="request-actions">${pill(r)}<button class="button small ${r.status==='pending'&&role==='manager'&&r.person!==who()?'primary':''}" data-action="${r.status==='pending'&&role==='manager'&&r.person!==who()?'review':'detail'}" data-id="${r.id}">${r.status==='pending'&&role==='manager'&&r.person!==who()?'去审批':'查看详情'}</button></div></div>`).join('')}</div>`;}
function recordTable(list){return list.length?`<div class="table-wrap"><table><thead><tr><th>申请人</th><th>假期类型</th><th>请假时间</th><th>时长</th><th>审批状态</th><th>操作</th></tr></thead><tbody>${list.map(r=>`<tr><td class="name"><div class="table-person">${avatar(r.person)}<div>${PEOPLE[r.person].name}<small>${r.id}</small></div></div></td><td>${TYPES[r.type]}</td><td>${dateRange(r)}</td><td>${r.days} 天</td><td class="status-cell">${pill(r)}</td><td><button class="table-actions" data-action="detail" data-id="${r.id}">查看详情</button></td></tr>`).join('')}</tbody></table></div>`:empty('没有符合条件的记录','试试其他关键词或筛选条件',true);}
function overview(){const b=balance(who(),'annual');const personal=own();const approved=records.filter(r=>r.status==='approved');const monthly=(role==='manager'?records:personal).filter(r=>r.created.startsWith('2026-09'));const list=role==='manager'?(dashTab==='pending'?pending():records.filter(r=>r.status!=='pending').slice(0,3)):personal.slice(0,3);return header(`${user().name}，工作与休息都从容`,'WORKSPACE OVERVIEW','2026 年 9 月 30 日，星期三 · 演示工作台')+`<section class="metrics" aria-label="请假概况">${metric(role==='manager'?'待我审批':'我的待审批',role==='manager'?pending().length:personal.filter(r=>r.status==='pending').length,'笔',role==='manager'?'及时处理，让安排更确定':'申请提交后，等待主管处理','clock')}${metric('本月申请',monthly.length,'笔','统计 9 月提交的申请','file')}${metric('我的年假余额',b.left,'天','已扣除审批中预占额度','sun')}${metric(role==='manager'?'即将休假':'我的已通过',role==='manager'?new Set(approved.filter(r=>r.start>BASE_DATE).map(r=>r.person)).size:personal.filter(r=>r.status==='approved').length,role==='manager'?'人':'笔',role==='manager'?'已批准的未来休假安排':'查看记录，提前安排交接','people')}</section><div class="dashboard-grid"><div><section class="panel"><div class="panel-head"><div><div class="panel-title"><h2>${role==='manager'?'审批待办':'我的申请'}</h2><span class="tiny-count">${role==='manager'?pending().length:personal.length}</span></div><p class="panel-sub">${role==='manager'?'每一份申请，都值得及时回应':'你的请假进度，随时掌握'}</p></div><button class="text-link" data-nav="${role==='manager'?'approvals':'records'}">查看全部</button></div>${role==='manager'?`<div class="tabs-line"><button data-tab="pending" class="${dashTab==='pending'?'active':''}">待处理 ${pending().length}</button><button data-tab="handled" class="${dashTab==='handled'?'active':''}">已处理</button></div>`:''}${requestRows(list)}</section><section class="panel lower-panel"><div class="panel-head"><h2>最近的请假记录</h2><button class="text-link" data-nav="records">全部记录</button></div>${recordTable((role==='manager'?records:personal).filter(r=>r.status!=='pending').slice(0,3))}</section></div><div class="side-stack">${annualCard()}${calendarCard()}</div></div>`;}
function getFiltered(){return (view==='approvals'?records.filter(r=>r.person!==who()):(role==='manager'?records:own())).filter(r=>(filter.status==='all'||r.status===filter.status)&&(filter.type==='all'||r.type===filter.type)&&(!filter.query||(PEOPLE[r.person].name+PEOPLE[r.person].dept+r.id+r.reason).toLowerCase().includes(filter.query.toLowerCase())));}
function recordsView(){const isApproval=view==='approvals';return header(isApproval?'审批中心':role==='manager'?'请假记录':'我的申请',isApproval?'APPROVAL CENTER':'LEAVE RECORDS',isApproval?'查看团队申请，安排好每一次交接':'所有申请与审批结果，一目了然')+`<section class="panel"><div class="filters"><div class="search-wrap">${icon('search')}<input id="searchInput" type="search" placeholder="搜索姓名、单号或事由" aria-label="搜索请假记录" value="${esc(filter.query)}"></div><select id="statusFilter" aria-label="按审批状态筛选"><option value="all">全部状态</option>${Object.entries(STATUSES).map(([k,v])=>`<option value="${k}" ${filter.status===k?'selected':''}>${v}</option>`).join('')}</select><select id="typeFilter" aria-label="按假期类型筛选"><option value="all">全部假期</option>${Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${filter.type===k?'selected':''}>${v}</option>`).join('')}</select><span class="filter-summary" id="resultCount"></span></div><div id="results"></div><div class="record-footer"><span>演示记录 · 仅保存在此浏览器</span><span>当前身份：${user().name} / ${role==='manager'?'部门主管':'员工'}</span></div></section>`;}
function updateResults(){const list=getFiltered();$('resultCount').textContent=`共 ${list.length} 条记录`;$('results').innerHTML=view==='approvals'?requestRows(list):recordTable(list);}
function balancesView(){return header('我的假期','MY TIME OFF','休息的时间，清晰可见 · 2026 年度')+`<div class="balance-grid">${['annual','comp'].map((type,i)=>{const b=balance(who(),type);return `<section class="panel balance-big"><h2>${TYPES[type]} <span class="tiny-count">年度额度 ${b.total} 天</span></h2><div class="donut" style="--ratio:${b.left/b.total*100};--blue:${i?'#4b9b94':'#315cd4'}"><div class="donut-inner"><strong>${b.left}</strong><span>可用天数</span></div></div><div class="balance-stats"><div><strong>${b.used}</strong>已批准</div><div><strong>${b.reserved}</strong>审批中</div><div><strong>${b.total}</strong>总额度</div></div></section>`}).join('')}<section class="panel balance-big"><h2>事假 <span class="tiny-count">按需申请</span></h2><div class="donut" style="--ratio:100;--blue:#b6c3d9"><div class="donut-inner"><strong>${own().filter(r=>r.type==='personal'&&r.status==='approved').reduce((s,r)=>s+r.days,0)}</strong><span>已批准天数</span></div></div><div class="balance-stats"><div><strong>—</strong>固定额度</div><div><strong>${own().filter(r=>r.type==='personal'&&r.status==='pending').reduce((s,r)=>s+r.days,0)}</strong>审批中</div><div><strong>0.5</strong>最小单位</div></div></section></div><section class="panel policy"><h2>假期使用说明</h2><ul><li>本演示的年假额度为 15 天，调休额度为 4 天；历史已用额度计入余额。</li><li>申请时预占额度，通过后转为已批准；驳回或撤回后释放额度。</li><li>最小请假单位为半天。仅计算周一至周五，未接入法定节假日与调休安排。</li><li>仅可申请 2026 年内、演示日期 9 月 30 日之后的假期；同一人的有效申请不能重叠。</li><li>所有规则均为演示设置，不代表真实劳动制度或企业政策。</li></ul></section>`;}
function render(){renderNav();$('main').innerHTML=view==='overview'?overview():view==='balances'?balancesView():recordsView();if(view==='approvals'||view==='records')updateResults();}
function openModal(title,body,footer=''){const dialog=$('modal');if(dialog.open)dialog.close();$('modalContent').innerHTML=`<div class="modal-header"><h2>${title}</h2><button class="icon-button" data-action="close" aria-label="关闭弹窗">×</button></div>${body}${footer?`<div class="modal-footer">${footer}</div>`:''}`;dialog.showModal();}
function closeModal(){$('modal').close();}
function formError(message){const e=$('formError');if(e){e.hidden=false;e.textContent=message;}}
function openApply(){openModal('发起请假',`<form id="leaveForm"><div class="modal-body"><div class="demo-warning">演示身份：${user().name} · 请勿填写真实员工资料或敏感信息</div><div class="form-grid"><div class="field full"><label for="leaveType">假期类型 <em>*</em></label><select id="leaveType" name="type">${Object.entries(TYPES).map(([k,v])=>`<option value="${k}">${v}${k!=='personal'?' · 可用 '+balance(who(),k).left+' 天':''}</option>`).join('')}</select></div><div class="field"><label for="startDate">开始时间 <em>*</em></label><div class="date-group"><input type="date" id="startDate" name="start" min="2026-09-30" max="2026-12-31" value="2026-10-15" required><select id="startHalf" name="startHalf" aria-label="开始时段"><option value="am">上午</option><option value="pm">下午</option></select></div></div><div class="field"><label for="endDate">结束时间 <em>*</em></label><div class="date-group"><input type="date" id="endDate" name="end" min="2026-09-30" max="2026-12-31" value="2026-10-15" required><select id="endHalf" name="endHalf" aria-label="结束时段"><option value="pm">下午</option><option value="am">上午</option></select></div></div><div class="field full"><label for="leaveReason">请假事由 <em>*</em></label><textarea id="leaveReason" name="reason" placeholder="简单说明假期安排与工作交接（演示内容即可）" maxlength="300" required></textarea></div></div><div class="form-info"><span>本次请假时长</span><strong id="durationLabel">1 天</strong></div><p class="form-hint">以周一至周五为工作日，最小单位 0.5 天。暂不计算法定节假日及调休，实际制度以企业规则为准。</p><div class="error-text" id="formError" role="alert" hidden></div></div><div class="modal-footer"><button type="button" class="button" data-action="close">取消</button><button class="button primary" type="submit">提交申请</button></div></form>`);}
function applyLeave(data){const d={person:who(),type:data.type,start:data.start,end:data.end,startHalf:data.startHalf,endHalf:data.endHalf,reason:String(data.reason||'').trim()};if(!TYPES[d.type]||!['am','pm'].includes(d.startHalf)||!['am','pm'].includes(d.endHalf))throw new Error('请选择有效的假期类型与时段');if(d.start<BASE_DATE||d.start>'2026-12-31'||d.end>'2026-12-31'||d.end<d.start)throw new Error('请选择 2026 年 9 月 30 日至 12 月 31 日内的有效日期');if(d.start===d.end&&d.startHalf==='pm'&&d.endHalf==='am')throw new Error('结束时段不能早于开始时段');d.days=duration(d.start,d.end,d.startHalf,d.endHalf);if(!d.days)throw new Error('所选时段不包含有效工作日，请重新选择');if(!d.reason||d.reason.length>300)throw new Error('请填写 1 至 300 字的演示事由');if(records.some(r=>r.person===d.person&&['pending','approved'].includes(r.status)&&overlaps(r,d)))throw new Error('所选时间与已有申请重叠，请换一个时段');if(d.type!=='personal'&&d.days>balance(d.person,d.type).left)throw new Error('可用假期余额不足，请缩短时长或选择其他类型');const serial=Math.max(108,...records.map(r=>Number(r.id.split('-').at(-1))||0))+1;const record={...d,id:'LF-2026-'+String(serial).padStart(4,'0'),status:'pending',created:BASE_DATE,note:''};records.unshift(record);save();render();return record;}
function submitReview(id,status,note){const r=records.find(r=>r.id===id);if(role!=='manager')throw new Error('请切换为部门主管身份后审批');if(!r||r.status!=='pending')throw new Error('这笔申请已经处理或不存在');if(r.person===who())throw new Error('主管不能审批自己的申请');if(!['approved','rejected'].includes(status))throw new Error('无效的审批结果');note=String(note||'').trim();if(status==='rejected'&&!note)throw new Error('请填写驳回原因，方便申请人调整');if(note.length>300)throw new Error('审批意见不能超过 300 字');r.status=status;r.note=note||(status==='approved'?'同意，请按计划完成交接。':'');r.reviewed=BASE_DATE;save();render();return {id:r.id,status:r.status};}
function openReview(id){const r=records.find(r=>r.id===id);if(!r)return;openModal('处理请假申请',`<div class="modal-body"><div class="detail-person">${avatar(r.person)}<div><strong>${PEOPLE[r.person].name}</strong><small>${PEOPLE[r.person].dept} · ${r.id}</small></div></div><div class="review-summary"><strong>${TYPES[r.type]} · ${r.days} 天</strong><br>${dateRange(r)}<br><span>${esc(r.reason)}</span></div><div class="field"><label for="reviewNote">审批意见 <span style="color:#99a5b5">（驳回时必填）</span></label><textarea id="reviewNote" maxlength="300" placeholder="请填写审批意见或需要调整的原因"></textarea></div><div class="error-text" id="formError" role="alert" hidden></div></div>`,`<button class="button" data-action="close">取消</button><button class="button danger" data-action="reject" data-id="${r.id}">驳回申请</button><button class="button primary" data-action="approve" data-id="${r.id}">通过申请</button>`);}
function openDetail(id){const r=records.find(r=>r.id===id);if(!r)return;openModal('请假详情',`<div class="modal-body"><div class="detail-person">${avatar(r.person)}<div><strong>${PEOPLE[r.person].name}</strong><small>${PEOPLE[r.person].dept} · ${r.id}</small></div><div style="margin-left:auto">${pill(r)}</div></div><dl class="detail-grid"><dt>假期类型</dt><dd>${TYPES[r.type]}</dd><dt>请假时间</dt><dd>${r.start} ${r.startHalf==='am'?'上午':'下午'}<br>至 ${r.end} ${r.endHalf==='am'?'上午':'下午'}</dd><dt>请假时长</dt><dd>${r.days} 天（工作日）</dd><dt>申请日期</dt><dd>${r.created}</dd><dt>请假事由</dt><dd>${esc(r.reason)}</dd>${r.note?`<dt>审批意见</dt><dd>${esc(r.note)}</dd><dt>处理日期</dt><dd>${r.reviewed}</dd>`:''}</dl>${r.status==='pending'?'<p class="form-hint">当前申请正在等待主管审批，额度已预占。</p>':''}</div>`,`${r.person===who()&&r.status==='pending'?`<button class="button danger" data-action="withdraw" data-id="${r.id}">撤回申请</button>`:''}<button class="button ${role==='manager'&&r.status==='pending'&&r.person!==who()?'':'primary'}" data-action="close">关闭</button>${role==='manager'&&r.status==='pending'&&r.person!==who()?`<button class="button primary" data-action="review" data-id="${r.id}">处理申请</button>`:''}`);}
function about(){openModal('关于这个演示',`<div class="modal-body"><p>这是休行请假管理的交互原型。你可以申请假期、切换主管与员工身份、审批申请和查看余额。</p><br><p>所有人物、公司与记录均为虚构。数据仅保存在当前浏览器，不会跨设备同步。这里没有真实登录、身份校验或多人协作后台；身份切换仅用于演示。</p><br><p>演示日期固定为 2026 年 9 月 30 日。计算仅区分工作日与周末，没有法定节假日及调休规则，不能直接作为人事核算依据。</p>${!storageAvailable?'<br><p>当前浏览器不支持保存，刷新后可能恢复初始数据。</p>':''}</div>`,'<button class="button primary" data-action="close">知道了</button>');}
function setRole(next){if(!['manager','employee'].includes(next))throw new Error('无效演示身份');role=next;closeModal();if(role==='employee'&&view==='approvals')view='records';save();render();return {role,person:user().name};}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-nav]');if(!b)return;if(b.dataset.nav){navigate(b.dataset.nav);return;}if(b.dataset.tab){dashTab=b.dataset.tab;render();return;}const id=b.dataset.id;switch(b.dataset.action){case'apply':openApply();break;case'close':closeModal();break;case'detail':openDetail(id);break;case'review':openReview(id);break;case'approve':case'reject':try{submitReview(id,b.dataset.action==='approve'?'approved':'rejected',$('reviewNote').value);closeModal();toast(b.dataset.action==='approve'?'申请已通过，假期余额已更新':'申请已驳回，预占额度已释放');}catch(error){formError(error.message);}break;case'withdraw':{const r=records.find(r=>r.id===id);if(r&&r.person===who()&&r.status==='pending'){openModal('撤回这笔申请？','<div class="modal-body"><p>撤回后将释放预占的假期额度，你可以重新发起申请。</p></div>',`<button class="button" data-action="close">暂不撤回</button><button class="button danger" data-action="confirm-withdraw" data-id="${id}">确认撤回</button>`);}break;}case'confirm-withdraw':{const r=records.find(r=>r.id===id);if(r&&r.person===who()&&r.status==='pending'){r.status='withdrawn';save();closeModal();render();toast('申请已撤回，预占额度已释放');}break;}case'clear-filters':filter={query:'',status:'all',type:'all'};render();break;case'confirm-reset':records=structuredClone(SEED);save();closeModal();render();toast('已恢复初始演示数据');break;}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){filter.query=e.target.value;updateResults();}if(['startDate','endDate','startHalf','endHalf'].includes(e.target.id))$('durationLabel').textContent=duration($('startDate').value,$('endDate').value,$('startHalf').value,$('endHalf').value)+' 天';});
document.addEventListener('change',e=>{if(e.target.id==='statusFilter'){filter.status=e.target.value;updateResults();}if(e.target.id==='typeFilter'){filter.type=e.target.value;updateResults();}if(['startDate','endDate','startHalf','endHalf'].includes(e.target.id))$('durationLabel').textContent=duration($('startDate').value,$('endDate').value,$('startHalf').value,$('endHalf').value)+' 天';});
document.addEventListener('submit',e=>{if(e.target.id==='leaveForm'){e.preventDefault();try{applyLeave(Object.fromEntries(new FormData(e.target)));closeModal();toast('申请已提交，假期额度已预占');}catch(error){formError(error.message);}}});
$('roleSelect').addEventListener('change',e=>{setRole(e.target.value);toast(`已切换为${user().name} · ${role==='manager'?'部门主管':'员工'}演示身份`);});$('profileBtn').addEventListener('click',()=>{setRole(role==='manager'?'employee':'manager');toast('已切换演示身份');});$('menuBtn').addEventListener('click',()=>$('sidebar').classList.toggle('open'));$('aboutBtn').addEventListener('click',about);$('resetBtn').addEventListener('click',()=>openModal('重置演示数据？','<div class="modal-body"><p>你在此浏览器中新增的申请与审批操作将清除，并恢复最初的虚构记录。</p></div>','<button class="button" data-action="close">取消</button><button class="button danger" data-action="confirm-reset">确认重置</button>'));
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});document.addEventListener('click',e=>{if(innerWidth<=700&&!e.target.closest('#sidebar')&&!e.target.closest('#menuBtn'))$('sidebar').classList.remove('open');});
const initial=location.hash.slice(1);if(['overview','approvals','records','balances'].includes(initial))view=initial;if(role==='employee'&&view==='approvals')view='records';render();
// Browser-native tools use the exact same demo actions as the interface.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(e){}};register({name:'list_leave_requests',title:'查看演示请假记录',description:'Read leave records visible to the currently selected demo role. Contains fictional records only.',inputSchema:{type:'object',properties:{status:{type:'string',enum:['all','pending','approved','rejected','withdrawn']}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(input.status&&!['all',...Object.keys(STATUSES)].includes(input.status))throw new Error('Invalid status');return {role,records:(role==='manager'?records:own()).filter(r=>!input.status||input.status==='all'||r.status===input.status).map(r=>({id:r.id,name:PEOPLE[r.person].name,type:TYPES[r.type],start:r.start,end:r.end,days:r.days,status:r.status}))};}});register({name:'submit_demo_leave_request',title:'提交演示请假申请',description:'Submit a fictional leave request as the selected demo user and reserve their local demo balance. Saves only in this browser.',inputSchema:{type:'object',properties:{type:{type:'string',enum:Object.keys(TYPES)},start:{type:'string',description:'YYYY-MM-DD, 2026-09-30 through 2026-12-31'},end:{type:'string',description:'YYYY-MM-DD'},startHalf:{type:'string',enum:['am','pm']},endHalf:{type:'string',enum:['am','pm']},reason:{type:'string',maxLength:300}},required:['type','start','end','startHalf','endHalf','reason'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{const r=applyLeave(input);toast('演示申请已提交');return {id:r.id,status:r.status,days:r.days};}});register({name:'review_demo_leave_request',title:'审批演示请假申请',description:'Approve or reject a pending fictional request as the manager demo role. A rejection needs a reason; self-approval is prohibited. Modifies browser-local demo data only.',inputSchema:{type:'object',properties:{id:{type:'string'},status:{type:'string',enum:['approved','rejected']},note:{type:'string',maxLength:300}},required:['id','status'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>submitReview(input.id,input.status,input.note)});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
